//! There is no netlink or kernel concept of "the system proxy" --
//! unlike addresses/routes/links, this is purely a userspace
//! convention. mitos-network's contribution is writing that convention
//! out consistently in the one place (`/etc/profile.d/`, shell-sourced
//! environment variables) every well-behaved Linux CLI tool already
//! knows to check, so every application doesn't need its own mitosOS
//! integration.

use crate::errors::Result;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ProxyMode {
    None,
    Manual,
    /// A PAC (proxy auto-config) URL.
    Auto,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProxyConfig {
    pub mode: ProxyMode,
    #[serde(default)]
    pub http: Option<String>,
    #[serde(default)]
    pub https: Option<String>,
    #[serde(default)]
    pub ftp: Option<String>,
    #[serde(default)]
    pub socks: Option<String>,
    #[serde(default)]
    pub no_proxy: Vec<String>,
    #[serde(default)]
    pub pac_url: Option<String>,
}

impl Default for ProxyConfig {
    fn default() -> Self {
        ProxyConfig { mode: ProxyMode::None, http: None, https: None, ftp: None, socks: None, no_proxy: Vec::new(), pac_url: None }
    }
}

const PROFILE_SCRIPT_PATH: &str = "/etc/profile.d/mitos-network-proxy.sh";

pub fn apply(cfg: &ProxyConfig) -> Result<()> {
    match cfg.mode {
        ProxyMode::None => clear(),
        ProxyMode::Manual => {
            let mut script = String::from("# Generated by mitos-network. Do not edit by hand.\n");
            for (var, value) in [("http_proxy", &cfg.http), ("https_proxy", &cfg.https), ("ftp_proxy", &cfg.ftp), ("all_proxy", &cfg.socks)] {
                if let Some(v) = value {
                    script.push_str(&format!("export {var}=\"{v}\"\n"));
                    script.push_str(&format!("export {}=\"{v}\"\n", var.to_uppercase()));
                }
            }
            if !cfg.no_proxy.is_empty() {
                let joined = cfg.no_proxy.join(",");
                script.push_str(&format!("export no_proxy=\"{joined}\"\n"));
                script.push_str(&format!("export NO_PROXY=\"{joined}\"\n"));
            }
            std::fs::write(PROFILE_SCRIPT_PATH, script)?;
            Ok(())
        }
        ProxyMode::Auto => {
            // A real PAC evaluator is a small JS engine's worth of work
            // (WPAD/PAC files are literally a `FindProxyForURL()`
            // JavaScript function) -- out of scope here. Recorded as a
            // known gap in docs/networking.md; `pac_url` is stored and
            // returned via IPC status queries so a future desktop
            // component can implement evaluation itself.
            clear()
        }
    }
}

pub fn clear() -> Result<()> {
    match std::fs::remove_file(PROFILE_SCRIPT_PATH) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.into()),
    }
}
