//! There is no netlink or kernel concept of "the system proxy" --
//! unlike addresses/routes/links, this is purely a userspace
//! convention. mitos-network's contribution is twofold: writing that
//! convention out consistently in the one place (`/etc/profile.d/`,
//! shell-sourced environment variables) every well-behaved Linux CLI
//! tool already knows to check, for the static (`Manual`) case; and,
//! for `Auto` (PAC), actually evaluating the script via `proxy::pac`
//! and exposing [`resolve_for_url`] -- a static env var fundamentally
//! can't represent "the answer depends on which URL you're asking
//! about", so anything that wants real per-URL PAC behavior has to
//! call in rather than read an exported variable.

use super::pac;
use crate::errors::{NetworkError, Result};
use serde::{Deserialize, Serialize};
use std::sync::Mutex;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ProxyMode {
    None,
    Manual,
    /// A PAC (proxy auto-config) URL.
    Auto,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProxyConfig {
    pub mode: ProxyMode,
    #[serde(default)]
    pub http: Option<String>,
    #[serde(default)]
    pub https: Option<String>,
    #[serde(default)]
    pub ftp: Option<String>,
    #[serde(default)]
    pub socks: Option<String>,
    #[serde(default)]
    pub no_proxy: Vec<String>,
    #[serde(default)]
    pub pac_url: Option<String>,
}

impl Default for ProxyConfig {
    fn default() -> Self {
        ProxyConfig {
            mode: ProxyMode::None,
            http: None,
            https: None,
            ftp: None,
            socks: None,
            no_proxy: Vec::new(),
            pac_url: None,
        }
    }
}

const PROFILE_SCRIPT_PATH: &str = "/etc/profile.d/mitos-network-proxy.sh";

/// The config `apply` last (successfully or not) attempted, and the
/// PAC script text fetched for it if mode was `Auto` -- what
/// [`resolve_for_url`] answers from, since a static shell script can't
/// represent a per-URL decision for the `Auto` case to read back.
static ACTIVE: Mutex<Option<ProxyConfig>> = Mutex::new(None);
static PAC_CACHE: Mutex<Option<String>> = Mutex::new(None);

pub fn apply(cfg: &ProxyConfig) -> Result<()> {
    *ACTIVE.lock().unwrap() = Some(cfg.clone());
    let result = apply_inner(cfg);
    if result.is_ok() {
        // Best-effort: a daemon restart should come back up with the
        // same proxy config rather than silently reverting to none,
        // but failing to persist that isn't a reason to fail the
        // apply itself (the config is live in `ACTIVE` either way).
        let _ = crate::persistence::state::save_proxy_config(cfg);
    }
    result
}

fn apply_inner(cfg: &ProxyConfig) -> Result<()> {
    match cfg.mode {
        ProxyMode::None => {
            *PAC_CACHE.lock().unwrap() = None;
            clear()
        }
        ProxyMode::Manual => {
            *PAC_CACHE.lock().unwrap() = None;
            let mut script = String::from("# Generated by mitos-network. Do not edit by hand.\n");
            for (var, value) in [
                ("http_proxy", &cfg.http),
                ("https_proxy", &cfg.https),
                ("ftp_proxy", &cfg.ftp),
                ("all_proxy", &cfg.socks),
            ] {
                if let Some(v) = value {
                    script.push_str(&format!("export {var}=\"{v}\"\n"));
                    script.push_str(&format!("export {}=\"{v}\"\n", var.to_uppercase()));
                }
            }
            if !cfg.no_proxy.is_empty() {
                let joined = cfg.no_proxy.join(",");
                script.push_str(&format!("export no_proxy=\"{joined}\"\n"));
                script.push_str(&format!("export NO_PROXY=\"{joined}\"\n"));
            }
            std::fs::write(PROFILE_SCRIPT_PATH, script)?;
            Ok(())
        }
        ProxyMode::Auto => {
            // No static env var can represent a per-URL PAC decision,
            // so there's nothing correct to write to the profile
            // script -- clear it rather than leave a stale Manual/None
            // one in place, and let resolve_for_url be the real
            // interface for Auto mode.
            clear()?;
            let Some(url) = &cfg.pac_url else {
                *PAC_CACHE.lock().unwrap() = None;
                return Err(NetworkError::Config(
                    "proxy mode is Auto but no pac_url is configured".into(),
                ));
            };
            let script = pac::fetch(url)?;
            // Fail fast on a script that won't parse at all, rather
            // than caching something resolve_for_url will just fail on
            // for every single URL later -- better to surface the
            // problem now, when there's a human action (fixing the
            // profile) that caused this call.
            pac::evaluate(&script, "http://example.com/", "example.com")
                .map_err(|e| NetworkError::Config(format!("PAC script at {url} is invalid: {e}")))?;
            *PAC_CACHE.lock().unwrap() = Some(script);
            Ok(())
        }
    }
}

pub fn clear() -> Result<()> {
    match std::fs::remove_file(PROFILE_SCRIPT_PATH) {
        Ok(()) => Ok(()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(e) => Err(e.into()),
    }
}

/// The currently-applied config, if `apply` has been called this run
/// -- for IPC status queries.
pub fn current() -> Option<ProxyConfig> {
    ACTIVE.lock().unwrap().clone()
}

/// Resolves which proxy (or `DIRECT`) a client should use for `url`,
/// honoring whichever mode is currently active. This -- not the
/// exported shell variables, which can't express it -- is what makes
/// `ProxyMode::Auto` an actually-usable feature rather than just a
/// stored URL: it evaluates the cached PAC script for `Auto`, formats
/// the static settings (respecting `no_proxy`) for `Manual`, and
/// returns `"DIRECT"` for `None` or for any evaluation failure -- a
/// broken or unreachable PAC script should degrade to no proxy, not
/// break every request through it.
pub fn resolve_for_url(url: &str) -> String {
    let cfg = ACTIVE.lock().unwrap().clone().unwrap_or_default();
    match cfg.mode {
        ProxyMode::None => "DIRECT".to_string(),
        ProxyMode::Manual => manual_directive(&cfg, url),
        ProxyMode::Auto => {
            let Some(script) = PAC_CACHE.lock().unwrap().clone() else {
                return "DIRECT".to_string();
            };
            let host = extract_host(url).unwrap_or_default();
            pac::evaluate(&script, url, &host).unwrap_or_else(|_| "DIRECT".to_string())
        }
    }
}

fn manual_directive(cfg: &ProxyConfig, url: &str) -> String {
    let host = extract_host(url).unwrap_or_default();
    if cfg.no_proxy.iter().any(|pat| host_matches_no_proxy(&host, pat)) {
        return "DIRECT".to_string();
    }
    let scheme = url.split(':').next().unwrap_or("http").to_ascii_lowercase();
    let chosen = match scheme.as_str() {
        "https" => cfg.https.as_ref().or(cfg.http.as_ref()),
        "ftp" => cfg.ftp.as_ref(),
        _ => cfg.http.as_ref(),
    };
    match chosen.or(cfg.socks.as_ref()) {
        Some(proxy) => format!("PROXY {proxy}"),
        None => "DIRECT".to_string(),
    }
}

fn host_matches_no_proxy(host: &str, pattern: &str) -> bool {
    let host = host.to_ascii_lowercase();
    let pattern = pattern.trim().to_ascii_lowercase();
    if pattern == "*" {
        return true;
    }
    let pattern = pattern.strip_prefix('.').unwrap_or(&pattern);
    host == pattern || host.ends_with(&format!(".{pattern}"))
}

/// A minimal URL-authority extractor (scheme, userinfo, port all
/// stripped) -- this crate has no full URL-parsing dependency, and PAC
/// resolution only ever needs the bare host.
fn extract_host(url: &str) -> Option<String> {
    let after_scheme = url.split_once("://").map(|(_, rest)| rest).unwrap_or(url);
    let authority = after_scheme.split(['/', '?', '#']).next().unwrap_or("");
    let authority = authority.rsplit_once('@').map(|(_, h)| h).unwrap_or(authority);
    if let Some(rest) = authority.strip_prefix('[') {
        // IPv6 literal, e.g. [::1]:8080.
        return rest.split(']').next().map(|s| s.to_string()).filter(|s| !s.is_empty());
    }
    let host = authority.split(':').next().unwrap_or(authority);
    if host.is_empty() { None } else { Some(host.to_string()) }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extract_host_handles_common_shapes() {
        assert_eq!(extract_host("http://example.com/path"), Some("example.com".to_string()));
        assert_eq!(extract_host("https://user:pass@example.com:8080/x"), Some("example.com".to_string()));
        assert_eq!(extract_host("http://[::1]:8080/"), Some("::1".to_string()));
        assert_eq!(extract_host("example.com:443"), Some("example.com".to_string()));
    }

    #[test]
    fn no_proxy_matches_subdomains() {
        assert!(host_matches_no_proxy("api.internal.example.com", ".example.com"));
        assert!(host_matches_no_proxy("example.com", "example.com"));
        assert!(!host_matches_no_proxy("evil-example.com", "example.com"));
        assert!(host_matches_no_proxy("anything.at.all", "*"));
    }
}
