//! Renders `zones`/`rules` down to an nftables ruleset and applies it
//! via `nft -f`. mitos-network owns exactly one table (`inet
//! mitos_network`) so it can atomically replace its own rules on every
//! change without disturbing anything unrelated another tool might have
//! configured in a different table.

use super::rules::{Action, Direction, Rule};
use super::zones::{DefaultPolicy, Zone};
use crate::errors::{NetworkError, Result};
use std::process::Command;

const TABLE_NAME: &str = "mitos_network";

fn nft_action(action: Action) -> &'static str {
    match action {
        Action::Accept => "accept",
        Action::Drop => "drop",
        Action::Reject => "reject",
    }
}

fn render_rule(rule: &Rule) -> String {
    let mut expr = String::new();
    if let Some(proto) = rule.protocol {
        expr.push_str(proto.nft_name());
        if let Some(port) = &rule.port {
            expr.push_str(&format!(" dport {} ", port.nft_expr()));
        } else {
            expr.push(' ');
        }
    }
    if let Some(src) = &rule.source {
        expr.push_str(&format!("ip saddr {src} "));
    }
    expr.push_str(nft_action(rule.action));
    expr
}

/// Renders the full ruleset. `masquerade_interfaces` are interfaces
/// that should NAT-masquerade outbound traffic (`sharing::nat` uses
/// this for internet-sharing hotspots); `forward_pairs` are
/// (lan_if, wan_if) pairs allowed to forward between each other (also
/// internet sharing).
pub fn render(zones: &[Zone], rules: &[Rule], masquerade_interfaces: &[String], forward_pairs: &[(String, String)]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by mitos-network. Do not edit by hand --\n");
    out.push_str("# changes here are overwritten on the next firewall reload.\n");
    out.push_str(&format!("table inet {TABLE_NAME} {{\n"));

    out.push_str("    chain input {\n");
    out.push_str("        type filter hook input priority 0; policy drop;\n");
    out.push_str("        ct state established,related accept\n");
    out.push_str("        ct state invalid drop\n");
    out.push_str("        iifname \"lo\" accept\n");

    for zone in zones {
        if zone.interfaces.is_empty() {
            continue;
        }
        let iface_set = zone.interfaces.iter().map(|i| format!("\"{i}\"")).collect::<Vec<_>>().join(", ");
        if zone.default_policy == DefaultPolicy::Accept {
            out.push_str(&format!("        iifname {{ {iface_set} }} accept\n"));
        }
        for rule in rules.iter().filter(|r| r.zone == zone.name && r.direction == Direction::Inbound) {
            out.push_str(&format!("        iifname {{ {iface_set} }} {}\n", render_rule(rule)));
        }
    }
    out.push_str("    }\n\n");

    out.push_str("    chain forward {\n");
    out.push_str("        type filter hook forward priority 0; policy drop;\n");
    out.push_str("        ct state established,related accept\n");
    for (lan, wan) in forward_pairs {
        out.push_str(&format!("        iifname \"{lan}\" oifname \"{wan}\" accept\n"));
    }
    out.push_str("    }\n\n");

    out.push_str("    chain output {\n");
    out.push_str("        type filter hook output priority 0; policy accept;\n");
    for rule in rules.iter().filter(|r| r.direction == Direction::Outbound) {
        out.push_str(&format!("        {}\n", render_rule(rule)));
    }
    out.push_str("    }\n");

    if !masquerade_interfaces.is_empty() {
        out.push_str("\n    chain postrouting {\n");
        out.push_str("        type nat hook postrouting priority 100;\n");
        for iface in masquerade_interfaces {
            out.push_str(&format!("        oifname \"{iface}\" masquerade\n"));
        }
        out.push_str("    }\n");
    }

    out.push_str("}\n");
    out
}

/// Applies a rendered ruleset by replacing mitos-network's own table
/// (`nft -f` on a script that starts with `table inet mitos_network {`
/// re-creates the table from scratch, which is exactly the atomic
/// full-replace semantics wanted here).
pub fn apply(ruleset: &str) -> Result<()> {
    // Best-effort: fails (harmlessly) with nothing to delete on the
    // very first apply after boot, which is fine -- errors from this
    // specific command are deliberately swallowed.
    let _ = Command::new("nft").args(["delete", "table", "inet", TABLE_NAME]).status();

    let path = std::env::temp_dir().join(format!("mitos-network-{}.nft", std::process::id()));
    std::fs::write(&path, ruleset)?;
    let status = Command::new("nft")
        .arg("-f")
        .arg(&path)
        .status()
        .map_err(|e| NetworkError::Firewall(format!("failed to run nft: {e}")))?;
    let _ = std::fs::remove_file(&path);
    if !status.success() {
        return Err(NetworkError::Firewall(format!("nft -f exited with {status}")));
    }
    Ok(())
}
